# Generated by Django 4.2.6 on 2023-11-01 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_commentpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentpost',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.post'),
        ),
    ]
