# Generated by Django 4.2.6 on 2023-11-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_commentpost_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentpost',
            name='post_id',
            field=models.CharField(max_length=500),
        ),
    ]
